### PR TITLE
Prepare for nuget

### PR DESCRIPTION
**Pull request by Mantus667**
Added nuspec file
Added config file
Update version number in project

### CODE REVIEW

**Comment by sotirisf** [comment]
Thanks for the PR - but is it wise to include the autonode.config file? (I've been struggling with this decision myself and I'm really not sure which is the correct answer to this). If users update to a later version, they may find their autonode.config file overwritten.

**Comment by Mantus667** [comment]
That is a good question indeed.
Normally nuget asks if it should overwrite the file when it detects changes I think.
So it would be the users decision.
Think I will test this to verfiy. 

Or you would keep it outside, not deliver it via nuget and the package makes a failsafe access to the file when it reads it. So also not quite sure what is the best way to handle this in general. But open to remove it again and only ship the dll then by nuget.

**Comment by sotirisf** [comment]
Well, if you have the time to do a test and verify that it prompts, we can leave it as it is. I'd do it, but I'm kind of up to the brink with work at the moment :( :(

**Comment by Mantus667** [comment]
Ok tested it with nuget installation and it prompts if the user wants to overwrite the file or not. So should be save to have the file in the project.

**Comment by sotirisf** [comment]
Merged! Thanks!

**Comment by sotirisf** [comment]
Sorry for being awfully late, package is on Nuget. https://www.nuget.org/packages/DotSee.AutoNode/1.4.0

**Pull request merged**
